version: '3'

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    network_mode: my-net
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_DB=payer
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    ##command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always