version: "3.1"

services:
  app:  
    build: './'
    stdin_open: true
    tty: true
    ports:
      - 9898:8001
    depends_on:
       - db
    env_file:
     - .env
   # environment:
   #   - DBUSER=${DBUSER}  
   #   - DBPASS=${DBPASS}
   #   - DBNAME=${DBNAME}
   #   - DBHOST=${DBHOST} 
    networks:
      - kafka
  
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DBUSER}  
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
      - DATABASE_HOST=${DBHOST} 
    #volumes:
    #  - database_postgres:/var/lib/postgresql/data
    networks:
      - kafka
    
networks:
  kafka:
    #external:
    #name: dockerized-kafka_kafka 
      #driver: bridge